name: Homomorphic tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache cargo registry
      uses: actions/cache@main
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache cargo index
      uses: actions/cache@main
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-index-

    - name: Install FFTW 
      run: sudo apt-get update && sudo apt-get install -y libfftw3-dev

    - name: Build and run tests
      run: cargo test --release homomorphic -- 5

    - name: Collect logs
      # if: failure()
      shell: bash
      run: |
        mkdir -p ./output-logs
        if [ -d "logs" ]; then
          cp -R logs/* ./output-logs/
        else
          echo "Log directory not found"
        fi

    - name: Upload logs to GitHub
      uses: actions/upload-artifact@main
      # if: failure()
      with:
        name: homomorphic-test-logs-${{ runner.os }}-${{ github.run_id }}
        path: ./output-logs/